[package]
name = "address-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
google_maps = "3.5.3"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
tokio = "1.38.0"
